import JSZip from "jszip";

function slugify(value) {
  return String(value || "kult-game")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "") || "kult-game";
}

function packageJsonFor(slug) {
  return JSON.stringify({
    name: slug,
    version: "1.0.0",
    private: true,
    type: "module",
    scripts: {
      dev: "vite --host 0.0.0.0",
      build: "vite build",
      preview: "vite preview"
    },
    dependencies: {
      "@vitejs/plugin-react": "^4.2.1",
      vite: "^5.0.12"
    },
    devDependencies: {}
  }, null, 2);
}

function indexHtmlFor(title) {
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${title}</title>
  </head>
  <body>
    <canvas id="game" tabindex="0" aria-label="${title} playable game"></canvas>
    <script type="module" src="/src/main.js"></script>
  </body>
</html>
`;
}

function readmeFor(gamePackage) {
  return `# ${gamePackage.title}

Playable Canvas export generated by KULT Creator Studio.

## Run Locally

\`\`\`bash
npm install
npm run dev
\`\`\`

Open the local Vite URL in your browser.

## Controls

- Move: WASD or arrow keys
- Action: Space or click/tap
- Restart: R

## Template

- Template: ${gamePackage.templateName}
- Type: ${gamePackage.templateId}
- Difficulty: ${gamePackage.customization?.difficulty ?? "normal"}
`;
}

function runtimeSource() {
  return `import { gamePackage } from "./gamePackage.js";
import "./styles.css";

const canvas = document.querySelector("#game");
const ctx = canvas.getContext("2d");
const WIDTH = 960;
const HEIGHT = 540;
const colors = gamePackage.visuals?.colors ?? ["#35e8ff", "#ff3df2", "#ffd166"];
const tuning = gamePackage.gameplay?.tuning ?? {};
const state = {
  score: 0,
  lives: 3,
  time: 30,
  over: false,
  message: "",
  player: { x: 160, y: 300, vx: 0, vy: 0, lane: 1 },
  items: [],
  shots: [],
  keys: new Set(),
  pointer: { x: 0, y: 0, pressed: false }
};

function resize() {
  const ratio = WIDTH / HEIGHT;
  const windowRatio = window.innerWidth / window.innerHeight;
  const cssWidth = windowRatio > ratio ? window.innerHeight * ratio : window.innerWidth;
  const cssHeight = cssWidth / ratio;
  canvas.style.width = cssWidth + "px";
  canvas.style.height = cssHeight + "px";
  canvas.width = WIDTH;
  canvas.height = HEIGHT;
}

function random(min, max) {
  return min + Math.random() * (max - min);
}

function clamp(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function reset() {
  state.score = 0;
  state.lives = 3;
  state.time = 30;
  state.over = false;
  state.message = "";
  state.player = { x: 160, y: 300, vx: 0, vy: 0, lane: 1 };
  state.items = Array.from({ length: 9 }, (_, index) => makeItem(index));
  state.shots = [];
  canvas.focus();
}

function makeItem(index = 0) {
  return {
    x: WIDTH + index * random(90, 170),
    y: random(145, HEIGHT - 80),
    r: random(16, 28),
    good: Math.random() > 0.32,
    lane: Math.floor(random(0, 3)),
    vy: random(-60, 60)
  };
}

function recycle(item) {
  Object.assign(item, makeItem());
}

function controlVector() {
  return {
    x: Number(state.keys.has("ArrowRight") || state.keys.has("KeyD")) - Number(state.keys.has("ArrowLeft") || state.keys.has("KeyA")),
    y: Number(state.keys.has("ArrowDown") || state.keys.has("KeyS")) - Number(state.keys.has("ArrowUp") || state.keys.has("KeyW")),
    action: state.keys.has("Space") || state.pointer.pressed
  };
}

function templateGroup() {
  if (["space-shooter", "ai-arena"].includes(gamePackage.templateId)) return "shooter";
  if (["runner", "racing", "cyber-runner"].includes(gamePackage.templateId)) return "runner";
  if (["flappy"].includes(gamePackage.templateId)) return "flappy";
  if (["clicker", "idle"].includes(gamePackage.templateId)) return "clicker";
  if (["match3", "memory", "quiz", "drawing", "minigames"].includes(gamePackage.templateId)) return "targets";
  return "targets";
}

function update(dt) {
  if (state.keys.has("KeyR")) reset();
  if (state.over) return;

  const input = controlVector();
  const mode = templateGroup();
  const speed = tuning.speed ?? 260;
  state.time -= dt;
  if (state.time <= 0) {
    state.over = true;
    state.message = "Time up";
  }

  if (mode === "flappy") {
    if (input.action) state.player.vy = -310;
    state.player.vy += 680 * dt;
    state.player.y += state.player.vy * dt;
    state.player.y = clamp(state.player.y, 120, HEIGHT - 30);
    moveItems(dt, speed);
  } else if (mode === "runner") {
    state.player.y = 230 + state.player.lane * 78;
    if (input.y !== 0) state.player.lane = clamp(state.player.lane + Math.sign(input.y), 0, 2);
    moveItems(dt, speed + 80);
  } else if (mode === "shooter") {
    state.player.x = clamp(state.player.x + input.x * 360 * dt, 40, WIDTH - 80);
    state.player.y = clamp(state.player.y + input.y * 300 * dt, 125, HEIGHT - 45);
    if (input.action && state.shots.length < 5) state.shots.push({ x: state.player.x + 28, y: state.player.y });
    state.shots.forEach(shot => { shot.x += 520 * dt; });
    state.shots = state.shots.filter(shot => shot.x < WIDTH + 20);
    moveItems(dt, speed + 20);
  } else if (mode === "clicker") {
    if (input.action) {
      const dx = state.pointer.x - WIDTH / 2;
      const dy = state.pointer.y - HEIGHT / 2;
      if (Math.hypot(dx, dy) < 96) state.score += 10;
    }
    state.items.forEach(item => {
      item.y += item.vy * dt;
      if (item.y < 145 || item.y > HEIGHT - 80) item.vy *= -1;
    });
  } else {
    state.player.x = clamp(state.player.x + input.x * 330 * dt, 40, WIDTH - 40);
    state.player.y = clamp(state.player.y + input.y * 260 * dt, 125, HEIGHT - 40);
    state.items.forEach(item => {
      item.x += Math.sin(performance.now() / 600 + item.y) * 30 * dt;
      item.y += item.vy * dt;
      if (item.y < 140 || item.y > HEIGHT - 80) item.vy *= -1;
    });
  }

  resolveCollisions();
}

function moveItems(dt, speed) {
  state.items.forEach(item => {
    item.x -= speed * dt;
    if (item.x < -50) recycle(item);
  });
}

function resolveCollisions() {
  state.items.forEach(item => {
    const targetX = templateGroup() === "clicker" ? state.pointer.x : state.player.x;
    const targetY = templateGroup() === "clicker" ? state.pointer.y : state.player.y;
    const hitPlayer = Math.hypot(item.x - targetX, item.y - targetY) < item.r + 24;
    const hitShot = state.shots.find(shot => Math.hypot(item.x - shot.x, item.y - shot.y) < item.r + 8);
    if (!hitPlayer && !hitShot) return;
    if (item.good || hitShot) {
      state.score += hitShot ? 25 : 10;
    } else {
      state.lives -= 1;
      state.message = state.lives > 0 ? state.lives + " lives left" : "Game over";
      if (state.lives <= 0) state.over = true;
    }
    recycle(item);
  });
}

function drawBackground() {
  ctx.fillStyle = "#070a12";
  ctx.fillRect(0, 0, WIDTH, HEIGHT);
  ctx.strokeStyle = colors[0] + "44";
  for (let x = 0; x <= WIDTH; x += 48) {
    ctx.beginPath();
    ctx.moveTo(x, 112);
    ctx.lineTo(x - 180, HEIGHT);
    ctx.stroke();
  }
  for (let y = 112; y <= HEIGHT; y += 42) {
    ctx.beginPath();
    ctx.moveTo(0, y);
    ctx.lineTo(WIDTH, y);
    ctx.stroke();
  }
}

function drawText(text, x, y, size = 22, color = "#eef6ff", align = "left") {
  ctx.fillStyle = color;
  ctx.font = "800 " + size + "px Inter, system-ui, sans-serif";
  ctx.textAlign = align;
  ctx.textBaseline = "middle";
  ctx.fillText(text, x, y);
}

function draw() {
  drawBackground();
  drawText(gamePackage.title, 28, 42, 22);
  drawText(gamePackage.gameplay?.mechanic ?? gamePackage.templateName, 28, 74, 16, "#91a4b8");
  drawText("Score " + Math.floor(state.score), 28, 106, 28);
  drawText("Lives " + state.lives, WIDTH - 28, 74, 20, "#91a4b8", "right");
  drawText(Math.ceil(state.time) + "s", WIDTH - 28, 106, 28, "#eef6ff", "right");

  if (templateGroup() === "clicker") {
    ctx.fillStyle = colors[0];
    ctx.beginPath();
    ctx.arc(WIDTH / 2, HEIGHT / 2, 84, 0, Math.PI * 2);
    ctx.fill();
    drawText("Click", WIDTH / 2, HEIGHT / 2, 28, "#061018", "center");
  } else {
    ctx.fillStyle = colors[0];
    ctx.beginPath();
    ctx.arc(state.player.x, state.player.y, 24, 0, Math.PI * 2);
    ctx.fill();
  }

  state.items.forEach(item => {
    ctx.fillStyle = item.good ? colors[1] : "#ff4d6d";
    ctx.beginPath();
    ctx.arc(item.x, item.y, item.r, 0, Math.PI * 2);
    ctx.fill();
  });

  ctx.fillStyle = colors[2] ?? "#ffd166";
  state.shots.forEach(shot => ctx.fillRect(shot.x, shot.y - 3, 20, 6));

  if (state.over) {
    ctx.fillStyle = "rgba(7,10,18,0.76)";
    ctx.fillRect(0, 0, WIDTH, HEIGHT);
    drawText(state.message || "Game Over", WIDTH / 2, HEIGHT / 2 - 20, 44, "#eef6ff", "center");
    drawText("Press R to restart", WIDTH / 2, HEIGHT / 2 + 32, 22, "#91a4b8", "center");
  }
}

let last = performance.now();
function frame(time) {
  const dt = Math.min(0.033, (time - last) / 1000);
  last = time;
  update(dt);
  draw();
  state.pointer.pressed = false;
  requestAnimationFrame(frame);
}

window.addEventListener("resize", resize);
window.addEventListener("keydown", event => {
  if (["ArrowUp", "ArrowDown", "ArrowLeft", "ArrowRight", "Space"].includes(event.code)) event.preventDefault();
  state.keys.add(event.code);
});
window.addEventListener("keyup", event => state.keys.delete(event.code));
canvas.addEventListener("pointerdown", event => {
  const rect = canvas.getBoundingClientRect();
  state.pointer.x = ((event.clientX - rect.left) / rect.width) * WIDTH;
  state.pointer.y = ((event.clientY - rect.top) / rect.height) * HEIGHT;
  state.pointer.pressed = true;
  canvas.focus();
});

resize();
reset();
requestAnimationFrame(frame);
`;
}

function runtimeSourceFor(gamePackage) {
  const generatedCode = gamePackage.refinement?.generatedCode;
  if (typeof generatedCode === "string" && generatedCode.trim()) {
    return generatedCode.trim() + "\n";
  }

  return runtimeSource();
}

function stylesSource() {
  return `:root {
  color-scheme: dark;
  font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
}

body {
  display: grid;
  place-items: center;
  min-height: 100vh;
  margin: 0;
  overflow: hidden;
  background: #070a12;
}

canvas {
  display: block;
  max-width: 100vw;
  max-height: 100vh;
  border: 1px solid rgba(53, 232, 255, 0.34);
  border-radius: 8px;
  outline: none;
  background: #070a12;
}

canvas:focus-visible {
  box-shadow: 0 0 0 2px rgba(53, 232, 255, 0.74);
}
`;
}

export async function buildGameCodeZip(gamePackage) {
  const title = gamePackage.title || "KULT Game";
  const slug = slugify(title);
  const zip = new JSZip();
  const root = zip.folder(slug);

  root.file("package.json", packageJsonFor(slug));
  root.file("index.html", indexHtmlFor(title));
  root.file("README.md", readmeFor(gamePackage));
  root.file("src/gamePackage.js", `export const gamePackage = ${JSON.stringify(gamePackage, null, 2)};\n`);
  root.file("src/main.js", runtimeSourceFor(gamePackage));
  root.file("src/styles.css", stylesSource());

  const buffer = await zip.generateAsync({ type: "nodebuffer" });
  return {
    buffer,
    filename: `${slug}-source.zip`
  };
}
