import { z } from "zod";
import { buildGameCodeZip } from "../services/codeExportService.js";
import { deleteGamePackage, listGamePackages, saveGamePackage } from "../services/databaseService.js";
import { createGamePackage } from "../services/gameFactoryService.js";
import { startJob } from "../services/jobService.js";
import { generateGameFromPrompt } from "../services/promptPipelineService.js";
import { createRefinementBundle } from "../services/refinementService.js";
import { generateAndStoreGameThumbnail } from "../services/thumbnailService.js";
import { logActivity } from "../services/activityService.js";

const createSchema = z.object({
  templateId: z.string().min(1),
  prompt: z.string().optional(),
  theme: z.string().optional(),
  difficulty: z.enum(["easy", "normal", "hard", "insane"]).optional(),
  customization: z.enum(["light", "medium", "heavy"]).optional(),
  extra: z.enum(["none", "powerups", "leaderboard", "boss"]).optional(),
  userId: z.string().optional()
});

const promptGenerateSchema = z.object({
  prompt: z.string().min(1),
  context: z.record(z.any()).optional(),
  theme: z.string().optional(),
  difficulty: z.enum(["easy", "normal", "hard", "insane"]).optional(),
  customization: z.enum(["light", "medium", "heavy"]).optional(),
  extra: z.enum(["none", "powerups", "leaderboard", "boss"]).optional(),
  includePlan: z.boolean().optional(),
  includeCode: z.boolean().optional(),
  includeAssets: z.boolean().optional(),
  strategy: z.string().optional(),
  userId: z.string().optional()
});

const refineSchema = z.object({
  gamePackage: z.record(z.any()),
  request: z.string().optional(),
  refinementLevel: z.string().optional()
});

const exportCodeSchema = z.object({
  gamePackage: z.record(z.any())
});

// Created games were previously only visible in the browser that generated
// them (localStorage). This lists what the backend actually saved so the
// frontend can show every creation.
export async function listGames(request, response, next) {
  try {
    const limit = Math.min(Number(request.query.limit) || 50, 100);
    const search = request.query.search || request.query.q;
    const games = await listGamePackages({ limit, search });
    response.json({ games });
  } catch (error) {
    next(error);
  }
}

const saveSchema = z.object({
  gamePackage: z.record(z.any())
});

// Saves an edited game (title, settings, code) from the post-creation editor.
export async function saveGame(request, response, next) {
  try {
    const input = saveSchema.parse(request.body);
    const gamePackage = { ...input.gamePackage, id: request.params.gameId };
    const persistence = await saveGamePackage(gamePackage);
    response.json({ ok: true, game: gamePackage, persistence });
  } catch (error) {
    next(error);
  }
}

export async function deleteGame(request, response, next) {
  try {
    const { deleted } = await deleteGamePackage(request.params.gameId);
    if (!deleted) {
      response.status(404).json({ error: "Game not found" });
      return;
    }
    response.json({ ok: true, deleted: request.params.gameId });
  } catch (error) {
    next(error);
  }
}

export async function createGame(request, response, next) {
  try {
    const input = createSchema.parse(request.body);
    const game = createGamePackage(input);
    game.creatorId = input.userId ?? request.auth?.userId ?? "anonymous";
    const persistence = await saveGamePackage(game);
    if (input.userId) {
      await logActivity({
        userId: input.userId,
        gameId: game.id,
        gameTitle: game.title,
        activityType: "create",
        details: `Created game "${game.title}" from template`
      });
    }
    response.status(201).json({ game, persistence });
  } catch (error) {
    next(error);
  }
}

export async function generateGame(request, response, next) {
  try {
    const input = promptGenerateSchema.parse(request.body);
    const result = await generateGameFromPrompt(input);
    // Attribute the game to its creator so follows and profile stats are real.
    result.game.creatorId = input.userId ?? request.auth?.userId ?? "anonymous";
    const persistence = await saveGamePackage(result.game);

    // Every generated game (hybrid and pure-agent) gets a real cover image:
    // generated by the image model, downloaded, and stored in the thumbnails
    // collection. Runs in parallel as a background job — the response is not
    // delayed, and the game record is updated when the image lands.
    const thumbnailJob = startJob("thumbnail-generation", () =>
      generateAndStoreGameThumbnail(result.game)
    );
    result.game.thumbnailJobId = thumbnailJob.id;
    if (input.userId) {
      await logActivity({
        userId: input.userId,
        gameId: result.game.id,
        gameTitle: result.game.title,
        activityType: "create",
        details: `Generated game "${result.game.title}" using AI`
      });
    }
    response.status(201).json({ ...result, persistence });
  } catch (error) {
    next(error);
  }
}

export async function refineGame(request, response, next) {
  try {
    const input = refineSchema.parse(request.body);
    const refinement = await createRefinementBundle(input);
    response.status(202).json({ refinement });
  } catch (error) {
    next(error);
  }
}

export async function exportGameCode(request, response, next) {
  try {
    const input = exportCodeSchema.parse(request.body);
    const { buffer, filename } = await buildGameCodeZip(input.gamePackage);

    response.setHeader("Content-Type", "application/zip");
    response.setHeader("Content-Disposition", `attachment; filename="${filename}"`);
    response.send(buffer);
  } catch (error) {
    next(error);
  }
}
